version: "3.3"

services:
    api:
        build: ./src
        ports:
            - "8090:8090"
        volumes:
            - ./src:/src
            - ../datasets:/datasets
        restart: always
        tty: true
        privileged: true
        command: python /src/main.py
